### ISSUE TITLE
連続フリックを一筆書きで入力したい

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#102]

**Comment by nobu-g** [comment]
isJudgeableFlickをなくすのはダメ？

**Comment by chomin** [comment]
新しいノーツとして追加したいかな

青ひし形とか、方向を指定するなら矢印とか

**Comment by nobu-g** [comment]
一筆書きできんとデレステ創作譜面できないから、仕様策定・実装急ぎたい

**Comment by nobu-g** [comment]
というかFlickクラスにleft, right, anyみたいなdirection列挙型持たせてもいいかも

内部はisJudgeableFlickを無視するとかかな

**Comment by chomin** [comment]
見た目が変わってくるしinit()で図形作ってるから、
Flickのprotocolを作って継承させるみたいな感じのほうが分かりやすそうな気がする(正直ここらへんは書きながら意見が変わっていきそうなところ)

ContinuableFlickにdirection持たせるのはあり

**Comment by chomin** [comment]
ちなみにデレステみたいにつなげたりするん？

**Comment by nobu-g** [comment]
initでswitch 分岐しよかと思ってた。挙動自体はFlickとあんまり変わらんし、新しいクラス作るまでしなくていいかなと。あとContinuableFlickとか名前長くなっちゃうのがなあ

ノーツ繋げるのは考えてない。プレイしづらかったら考える

**Comment by nobu-g** [comment]
protocolとかやるならNoteクラス群大掃除してもいいかも(Flickプロトコル, Startプロトコル, Followerプロトコルとか)

**Comment by chomin** [comment]
確かに。

よく見たらFlickの中身ほぼ無いしプロトコルいらんな

2018/09/27 17:07、nobu-g <notifications@github.com>のメール:

protocolとかやるならNoteクラス群大掃除してもいいかも(Flickプロトコル, Startプロトコル, Followerプロトコルとか)

**Comment by chomin** [comment]
とりあえず原型だけでもこっちで作っといたほうがいいかな？

**Comment by nobu-g** [comment]
原型といわずできるなら全部作ってもらいたいぐらいやけど笑

**Comment by nobu-g** [comment]
上フリックはscoreGenerator書き直すのめんどいからなし(精度落ちるし)
bmsはわかりにくいかもやけど特大ノーツの次に割り当てればいいかなというとこ
色はとりあえずつけといたら？(修正簡単やし)

**Comment by chomin** [comment]
おｋ

とりあえず作り始めてみるわ

**Comment by chomin** [comment]
tapLLの定義が"0G"になってるけど、何進数にする感じなん？そのまま"0Z"とかまで進めちゃう？

**Comment by nobu-g** [comment]
エディターがたしか0Zまであったからそれでいいと思う
数値じゃなくてラベルみたいなもんやし

**Comment by nobu-g** [comment]
なんでしょう

**Comment by chomin** [comment]
定義はこれでいいかなって

**Comment by nobu-g** [comment]
rightとrightEnd分ける理由は？

**Comment by chomin** [comment]
startからつながるやつあるやん

もしかしてそれもなし？

**Comment by chomin** [comment]
miiddle.rightとか作ったら見た目だけつなげるってできそう

**Comment by nobu-g** [comment]
startからつながるやつは今までのmiddleでいいかなって思ってたけど確かに色違うと気持ち悪いな

つなげたかったらつなげてくれてもおk

**Comment by chomin** [comment]
そもそもmiddle終わりだとパースできないからTapEndになるけどな

繋げる場合、場合分けが大変やし(FlickStartから始まった場合は)middleとかを禁止する方向でおｋ？

**Comment by nobu-g** [comment]
middleじゃなかったflickEnd

**Comment by chomin** [comment]
middle.rightが発生したあとも

**Comment by nobu-g** [comment]
？あんまり分かってない
連フリックの途中からMiddleが発生する？

**Comment by chomin** [comment]
ってよりTapStartからmiddle.flickがつながるときやな

**Comment by chomin** [comment]
middleの処理が複雑になりそうやなー
デレステの縦判定ゆるゆるなのもココらへんと関係ありそう

やっぱ一旦パスで

**Comment by nobu-g** [comment]
「う〜がお〜」の話？

**Comment by chomin** [comment]
FlickStart → 緑middle, TapEnd, ピンクFlickEnd
TapStart → (左右middle) → 緑middle, TapEnd, ピンクFlickEnd
TapStart → (左右middle) → 左右FlickEnd

上から××○

**Comment by nobu-g** [comment]
やっぱり難しい
まあパスってことで
