### ISSUE TITLE
pickerのUIの変更

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#107]
上の方まで出したり色分けしたりプレイ回数やフルコンや難易度を表示したり…

**Comment by chomin** [comment]
上の方まで出すやり方が分からん

他は何とかなりそう

**Comment by chomin** [comment]
ピッカーを使うのをやめてライブラリを探す。

横書きなので縦にスライドさせるのが良い

**Comment by nobu-g** [comment]
自由度あっていい感じやね

**Comment by chomin** [comment]
- 色分け

- ランダム選択

**Comment by nobu-g** [comment]
色分け完了
