### ISSUE TITLE
【急募】No such module 'youtube_ios_player_helper'

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#113]
pod install しても直らない。

https://blog.yukim.xyz/post/2015-09-18-how-to-uninstall-cocoapods/

↑に従ってcocoapodsの再インストールからやり直したけど直らない。

プロジェクトのpod関係ファイルを全部消して、
https://developers.google.com/youtube/v3/guides/ios_youtube_helper#manually-install-the-library

↑のManually install the libraryしても直らない。

万策尽きた〜 <(´ﾟдﾟ`)>

**Comment by chomin** [comment]
XCodeのベータ版が問題だった。リリース版なら通常通り起動できた

**Comment by chomin** [comment]
nobuが今度はRealmSwiftについてNo such moduleが発生

**Comment by chomin** [comment]
https://github.com/CocoaPods/CocoaPods/issues/8073

**Comment by nobu-g** [comment]
pod repo updateで解決

**Comment by chomin** [comment]
_No such module 'RealmSwift'_

**Comment by chomin** [comment]
"""
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
"""

で直った。

_:-1: linker command failed with exit code 1 (use -v to see invocation)_

が新たに発生

**Comment by chomin** [comment]
: - 1 : でfu○kなんか

**Comment by nobu-g** [comment]
こっちは問題ないな

**Comment by chomin** [comment]
_: -1: linker command failed with exit code 1 (use -v to see invocation)_

はシミュレーター用でビルドすると発生するみたい（alureのcmakeの設定で実機ビルドのみに対応するようにしたせい）
実機をつなげるかビルド用deviceに設定することで解決

**Comment by chomin** [comment]
```
ld: warning: directory not found for option '-L/Users/NakaiKohei/alure-1.2/build'
Undefined symbols for architecture arm64:
  "_alureInitDevice", referenced from:
      音ゲー_仮_.ActionSoundPlayers.init() -> 音ゲー_仮_.ActionSoundPlayers in Sounds.o
  "_alurePauseSource", referenced from:
      音ゲー_仮_.SoundSource.pause() -> () in Sounds.o
  "_alurePlaySource", referenced from:
      音ゲー_仮_.SoundSource.play() -> () in Sounds.o
  "_alureStopSource", referenced from:
      音ゲー_仮_.SoundSource.deinit in Sounds.o
      音ゲー_仮_.SoundSource.stop() -> () in Sounds.o
  "_alureCreateBufferFromFile", referenced from:
      音ゲー_仮_.SoundSource.init(fullFilePath: Swift.String) -> 音ゲー_仮_.SoundSource? in Sounds.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

実機をつなげてもビルド用デバイスでも起きる、、、

**Comment by chomin** [comment]
```
clang: error: no such file or directory: '/Users/NakaiKohei/alure-1.2/build/alure.o'
clang: error: no such file or directory: '/Users/NakaiKohei/alure-1.2/build/buffer.o'
clang: error: no such file or directory: '/Users/NakaiKohei/alure-1.2/build/codec_aiff.o'
clang: error: no such file or directory: '/Users/NakaiKohei/alure-1.2/build/streamdec.o'
clang: error: no such file or directory: '/Users/NakaiKohei/alure-1.2/build/stream.o'
clang: error: no such file or directory: '/Users/NakaiKohei/alure-1.2/build/streamplay.o'
clang: error: no such file or directory: '/Users/NakaiKohei/alure-1.2/build/codec_wav.o'
clang: error: no such file or directory: '/Users/NakaiKohei/alure-1.2/build/istream.o'
```

該当場所に各ファイルは存在

**Comment by nobu-g** [comment]
Build Settings -> Library Search Paths とかでは？

**Comment by chomin** [comment]
そこは弄ってないけど、とりあえずファイルをプロジェクトフォルダにコピーして認識させた

**Comment by chomin** [comment]
> There is two errors that people seem to be confused with
>If it is a "directory not found for option '-L/..." error That means it's a Library Error, and you should try  to:
>Click on your project (targets) Click on Build Settings Under Library Search Paths, delete the paths.
>If it is a "directory not found for option '-F/..." That means it's a Framework Error, and you should try to:
>Click on your project (targets) Click on Build Settings Under Frameworks Search Paths, delete the paths

[こちら](https://stackoverflow.com/questions/20480571/xcode-directory-not-found-for-option-l-errors/24036222#24036222l)より

**Comment by chomin** [comment]
No such module 'GTMAppAuth'

これで何回目やろ、、、

**Comment by chomin** [comment]
Targets → Build Phases → Link Binary With Libraries
に追加されてなかった()
