### ISSUE TITLE
ファイルをフォルダに分けて整理する

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#126]
例えば、

ユーザインタフェース層：ユーザと直接対話するためのクラス（バウンダリ・クラス）を置く．
アプリケーション層：ユースケースのイベントフローを実現するクラス（コントロール・クラス）を置く．
ドメイン層： 分析レベルで抽出されたモノを表すクラス（エンティティ・クラス）を置く．

に従って、uiフォルダにSceneクラスを、appフォルダにparcerクラスを、entityフォルダにPickerKeyboardとかYTPlayerViewHolderとかNoteとかLaneとかを、othersフォルダに他のやつをいれるとか？

**Comment by nobu-g** [comment]
大きいプロジェクトならそうなんかも知れんけど、正直この規模でわざわざファイル階層深くしなくていいと思う

**Comment by chomin** [comment]
ファイル数2桁やし結構多くね？

2018/08/22 1:19、nobu-g <notifications@github.com>のメール:

大きいプロジェクトならそうなんかも知れんけど、正直この規模でわざわざファイル階層深くしなくていいと思う

**Comment by nobu-g** [comment]
そんなに不便感じてないねんなあ
深くするとフォルダ辿る手間が増える

**Comment by chomin** [comment]
今は覚えてるからいいけど時間経って見返す時に発狂しそう

まあ一旦保留で

2018/08/22 2:42、nobu-g <notifications@github.com>のメール:

そんなに不便感じてないねんなあ
深くするとフォルダ辿る手間が増える

**Comment by nobu-g** [comment]
ちなみに、最初の「例えば、」の難しい話はソースどこ？

**Comment by chomin** [comment]
学校のJavaの授業のやつ

パッケージの作り方的な

2018/08/22 3:06、nobu-g <notifications@github.com>のメール:

ちなみに、最初の「例えば、」の難しい話はソースどこ？
