### ISSUE TITLE
ChooseMusicSceneのインスタンスの量産を解消

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#128]
GameSceneとかResultSceneとかも含めてシングルトン化してstatic使いまくるのが一番早い気がするけど保守性があれなんよな

なんかいい方法ないかな

**Comment by nobu-g** [comment]
インスタンス量産ってメモリリークしてるってこと？
してないなら触らんでいいと思うけど

**Comment by chomin** [comment]
ボタンとか選択した曲とか全部初期化されるからどっかで保持しよう的な話してたやつ

2018/08/23 12:54、nobu-g <notifications@github.com>のメール:

インスタンス量産ってメモリリークしてるってこと？
してないなら触らんでいいと思うけど

**Comment by chomin** [comment]
せやな。曲選択以外はもう作った。
曲選択はpickerの問題があるかもやから後で格闘してみる

2018/08/23 13:24、nobu-g <notifications@github.com>のメール:

インスタンス保持より、設定をストレージに書き出しといたらいいかと

**Comment by chomin** [comment]
以後は
#105 
で議論する
