### ISSUE TITLE
判定系の処理を非同期でサブスレッドのキューに追加するとバグる

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#129]
バグるが、CPU Frame Timeはすごく小さくなるので非同期でやりたい。
judgeQueue.syncで追加すると上手くいく。
judgeQueue = DispatchQueue.mainと、メインスレッドで処理を行うようにすると、
judgeQueue.async { } でも上手くいく。謎。

**Comment by chomin** [comment]
バグるとは？

**Comment by nobu-g** [comment]
判定線通過前なのに何もしてなくてもmiss判定されたり、
途中でノーツが消失したり、
最悪落ちる

**Comment by chomin** [comment]
Thread 3: UIView.superview must be used from main thread only
って出てくるな

多分やけどsyncならキューを分けてもメインスレッドに処理が投げられるけど、asyncにしたら空いてるスレッドにバラバラに処理が投げられるとかじゃないかな。少なくともUITouchループはasyncにできなさそう。

asyncにしてforが入れ子になってる場合にどんな感じで処理が分割されるのか知らないとバグの温床になりそう。

**Comment by nobu-g** [comment]
自分の理解ではsyncならブロック内の処理が終わってから次の処理に移るけど、asyncならひとまずキューに追加しといて実行を待たずにブロックの下の処理を始めちゃうって感じ。同じことかも
UITouchループがasyncにできないのはなぜ？

**Comment by chomin** [comment]
https://qiita.com/ShoichiKuraoka/items/bb2a280688d29de3ff18#メインディスパッチキュー

によると

同期的：タスクをディスパッチキューに追加したあと、そのタスクの処理完了まで次の行に移行しない。（つまり、通常の記述と同じ）
非同期的：タスクをディスパッチキューに追加したら、そのタスクの処理完了を待たずに次の行に移行する。

ってことでブロック単位じゃなくて行単位で並列化されるみたい。


UITouchループがasyncにできないのは、21行目で座標を取得するためにself.view?.superviewを呼び出してるから、規約によってmainスレッドでの処理に制限されるからかな。予め座標を取得しといて配列か何かに入れてループ回すならいけるかも

**Comment by chomin** [comment]
https://qiita.com/koji-nishida/items/14fda04b586263a47e73

queue作成の時に

, attributes: .concurrent)

ってするとブロック単位の並列処理になるみたい


2018/08/28 19:32、nobu-g <notifications@github.com>のメール:

自分の理解ではsyncならブロック内の処理が終わってから次の処理に移るけど、asyncならひとまずキューに追加しといて実行を待たずにブロックの下の処理を始めちゃうって感じ。同じことかも
UITouchループがasyncにできないのはなぜ？

**Comment by nobu-g** [comment]
同期・非同期の記事はわかりやすくするために「行」っていう表現を使ってると思う(syncブロックの}から見て次の行)。そもそも機械語がソースコードの行なんていうメタデータ持ってるとは思えんし。
.attributes: .concurrentはデフォルトで直列の、main以外のdispatchQueueを並列にするためのオプションでは？

**Comment by chomin** [comment]
あーなるほど。ブロック単位っぽいね。

syncのときは直列処理だから結局mainスレッドと足並みをそろえることになるからjudgeQueueにメインスレッドを割り当ててたけど、
asyncではjudgeQueueにメインとは別のスレッドを割り当てて並列処理してるって感じかな。んで今回はThread3が割り当てられた。


attributes: .concurrentについてやけど、
https://dev.classmethod.jp/smartphone/iphone/swift-3-how-to-use-gcd-api-1/
には

Serial
処理を直列に実行する。キュー内の前の処理が完了してから次の処理が開始する。一度に実行される処理は一つのみ。
Concurrent
処理を並列に実行する。処理がキューから取り出される順番はFIFOだが、一度に複数の処理が実行され、処理が完了する順番もバラバラ。

って書いてあって、ソース忘れたけど別のサイトには
「Serialにすると1つのスレッドが割り当てられ、Concurrentにすると複数のスレッドが割り当てられる」
って書いてあったから、キューに追加されたブロック同士を直列に並列or直列に処理するかのオプションかな（同じことかもしれんけど）。

**Comment by nobu-g** [comment]
「syncのときは直列処理」というか「syncのときは同期処理」かな。イメージは直列処理やけど
まあそんな感じかと

concurrentの話は同じことやと思う。
音ゲーの場合はタッチした順番が大事やから並列にはできない。

あと、Thread 3: UIView.superview must be used from main thread only のエラー一瞬見た気がするけど今は出てない。なんでやろ

**Comment by chomin** [comment]
concrrentについては同意。judge自体は時間記録してるから正確にできるけど、その後の判定ラベル表示がぐちゃぐちゃになる。

2018/08/28 22:16、nobu-g <notifications@github.com>のメール:

「syncのときは直列処理」というか「syncのときは同期処理」かな。イメージは直列処理やけど
まあそんな感じかと

concurrentの話は同じことやと思う。
音ゲーの場合はタッチした順番が大事やから並列にはできない。

あと、Thread 3: UIView.superview must be used from main thread only のエラー一瞬見た気がするけど今は出てない。なんでやろ

**Comment by nobu-g** [comment]
> スレッドの割当はシステムが各スレッドの使用状況に応じて自動的に割り当てるから、たまたまメインスレッドを割り当てることもあるってことなのかな？

Thread 3: UIView.superview must be used from main thread only ってランタイムエラーじゃないよな？

**Comment by chomin** [comment]
ランタイムやで
