### ISSUE TITLE
収録曲のヘッダ情報をDBで管理

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#137]

**Comment by nobu-g** [comment]
ファイル更新チェック→
更新があればヘッダ情報をDBに追加→
DBを読んでCMSceneを作成→
曲選択→
BMS(主にメインデータ)読み込み

って感じでOK？

**Comment by chomin** [comment]
オッケー！

とーてーもーすーてきなー

**Comment by nobu-g** [comment]
Realmってのがよさそう(うたがこーこにー
[Realm日本語ドキュメント(旧版)](https://realm.io/jp/docs/swift/latest)
[qiita](https://qiita.com/kazuhiro1128/items/332770987e20a8248bc3)

**Comment by nobu-g** [comment]
あと、データはサーバーに上げる？
具体的なやり方全くわからんけども
サーバーから更新日時を取ってくる仕組みも必要

**Comment by chomin** [comment]
サーバーに上げるやつは追々実装したら良さそう

**Comment by chomin** [comment]
[ここ](https://qiita.com/YamagishiRyu/items/5667ea8b87beb4792469)に従ってAlcatrazを導入しようとしたらxcodeが開かなくなった・・・

**Comment by nobu-g** [comment]
podsでいいじゃん

**Comment by chomin** [comment]
入んない

**Comment by chomin** [comment]
Alcatrazはxcodeのプラグインね

**Comment by chomin** [comment]
Objective-C使わないからRealmじゃなくてRealmSwift使っていい？

**Comment by chomin** [comment]
どういえばBPMsはヘッダとメインの両方に書いてあるけどDBに保存する方向でおｋ？

**Comment by nobu-g** [comment]
曲選択の時に使わないならDBには置いとかんでもよくない？

**Comment by chomin** [comment]
http://somen.site/2018/02/02/realmswiftの使い方永久保存版-swift4-0/#deleteAll

参考サイト
