### ISSUE TITLE
タイミング調整機能の追加

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#143]

**Comment by chomin** [comment]
1. 中断画面で調節して最初から再生し直す
2. 調節モードを作って自動再生しながら調節する

どっちがいいかな

**Comment by chomin** [comment]
GameScene分解するのはどう？

GameScene, AutoPlayScene, OffsetSceneでそれぞれGameSceneProtocolを継承するとか

**Comment by chomin** [comment]
#160 もOffsetSceneでできたらなーって考えてる

**Comment by nobu-g** [comment]
OffsetSceneの使い道が分からんけど、分解するのは賛成
共通のプロパティ持ちたいと思うし、protocol よりは 普通の class か？

**Comment by chomin** [comment]
offsetシーンでは自動再生しながら調節ボタン押して保存的なことを考えてる。

親クラス作ってもインスタンス化しないからプロトコルの方が分かりやすいって思った。関数もextensionでは標準の処理内容を記述できるし

**Comment by chomin** [comment]
プロパティは無理やっけ？共有って例えば何があるやろ

**Comment by nobu-g** [comment]
個人的にはクラス継承かなって気がしてる
https://www.slideshare.net/mobile/tomohirokumagai54/swift-yidev

**Comment by chomin** [comment]
そもそもGame **Scene** Protocolって名前がナンセンスやな。「譜面とか音楽を再生するプロトコル」って感じが良さそう。

親クラス作るとSKScene(クラス)が親子じゃなくて祖父母孫関係になるからプロトコルがいいかな。親をシーンとして使うわけじゃないのにシーンとして作ることに違和感。

**Comment by chomin** [comment]
祖父母孫とか親子についてはむしろ親を~Sceneとしたら解決できるんか

**Comment by chomin** [comment]
親・・・曲or映像とノーツを流す。レーンを表示。判定アニメーション。

GameScene・・・タップを受け付け、判定する。Resultの作成。
AutoPlayScene・・・Perfectのタイミングで判定。Resultの作成。
OffsetScene・・・Perfectのタイミングで判定。ボタンを押して曲と譜面のタイミングを少しずらす(ずらすたびに最初から再生し直し？)。YouTubeと簡単に切替可能。ずらした結果をDBに保存。

**Comment by chomin** [comment]
親をクラスにしちゃったほうが楽そうにも見える。悩ましいところ。

**Comment by chomin** [comment]
> 個人的にはクラス継承かなって気がしてる
> https://www.slideshare.net/mobile/tomohirokumagai54/swift-yidev

このスライド見ても設計次第でどっちでもいい気がするけど、クラス継承だと思うのはどのあたり？

**Comment by chomin** [comment]
プロトコルってjavaでいうインターフェイスみたいなものやと思ってたけど、storedプロパティを宣言すらできないのか、、、

諦めてクラスにしまふ
