### ISSUE TITLE
Soundsフォルダの中身を鯖に上げる

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#147]

**Comment by nobu-g** [comment]
手法メモ

Google Driveに上げて、アプリからGoogle Drive APIを叩くのが良さげ

その他の方法
- 他のクラウドストレージサービス(京大のNextCloudは容量無制限)
- Google Cloud Strage(本格的・ほんのちょっと料金がかかる)
- Google Compute Engine(ガチ・学習コストがかかる)

**Comment by chomin** [comment]
Googleの共用垢でも作るか

**Comment by nobu-g** [comment]
それはありかと

**Comment by chomin** [comment]
### 参考サイト
https://paveway.hatenablog.com/entry/2018/07/28/swift_googledrive_get_file_data

**Comment by chomin** [comment]
### 画面遷移
タイトル画面→（ローカルファイル探索）→無い曲・譜面があればポップアップ「ダウンロード？Yes/Cancel」→ダウンロード画面（非同期）→ChooseMusicScene

**Comment by chomin** [comment]
そうしよか

play→「ダウンロードします。Yes/Cancel/今後は表示しない」

**Comment by chomin** [comment]
認証にはOAuthを使う。
起動→safariでログイン→(ファイル一覧を取得)→曲選択→play→「ダウンロードします。Yes/Cancel/今後は表示しない」

**Comment by chomin** [comment]
ファイル一覧取得時に、bmsは差分をダウンロード・保存する。
（ChooseMusicSceneで使うため。ヘッダ情報はrealmデータベースに保存）

CMSceneにおいて、mp3がダウンロードされていない場合は選択スロットで分かりやすくし（文字を薄くするとか背景色を変えるとか）、ボタンの文字「この曲で遊ぶ」を「曲をダウンロードして遊ぶ」に変える。

**Comment by chomin** [comment]
残りは

- staticを減らす
- ファイルの中身が更新されたら反映させる
