### ISSUE TITLE
YouTubeモードが無理な曲は切り替えボタンを非アクティブに

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#149]
VideoIDもheaderで持たせて、VideoIDがなければ非アクティブにするという感じで

現状、VideoIDがない曲でYouTubeモードを選択した時に自動でBGMモードになる機能が働いていないので。。。(というか働かせるのが難しい)

**Comment by chomin** [comment]
おけ

裏シオンあるから2つ分持たせる必要あるな

2018/09/05 22:10、nobu-g <notifications@github.com>のメール:

VideoIDもheaderで持たせて、VideoIDがなければ非アクティブにするという感じで

現状、VideoIDがない曲でYouTubeモードを選択した時に自動でBGMモードになる機能が働いていないので。。。(というか働かせるのが難しい)

**Comment by chomin** [comment]
ついでにpickerにも☆付けるとかして分かりやすくしたいな
