### ISSUE TITLE
「Welcome to・・・ わーい！」でノーツが残る

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#151]

**Comment by chomin** [comment]
観測できないんやけど、どういう条件とかある？

**Comment by nobu-g** [comment]
高速にスライドした時？

**Comment by nobu-g** [comment]
まだmasterでは起こらんかも

**Comment by chomin** [comment]
多分観測できたけど、長押し円が残るってのであってる？

2018/09/06 12:06、nobu-g <notifications@github.com>のメール:

まだmasterでは起こらんかも

**Comment by nobu-g** [comment]
あってる
緑円がちょっとずれて残る

**Comment by chomin** [comment]
んでその後は50fpsに落ちてタッチしても反応しないことがあったり、落ちたりするって感じか

2018/09/07 14:34、nobu-g <notifications@github.com>のメール:

あってる
緑円がちょっとずれて残る

**Comment by nobu-g** [comment]
いや、ノーツが残るだけでそのあとは正常やと思ったけど。
タッチの反応が数秒単位で遅れるみたいな現象は一時停止した時に起こる

**Comment by chomin** [comment]
いや、フレーム落ち&反応しなくなるのは残るやつの前でも起きるな

**Comment by nobu-g** [comment]
一時停止して再開した時やんな？

**Comment by chomin** [comment]
いや普通にプレイしてていきなり

**Comment by nobu-g** [comment]
それは確認してないな

**Comment by chomin** [comment]
critical sectionの洗い出し&相互排除
をもう一回確認するか
