### ISSUE TITLE
BPMに応じてスピードが変わるようにする

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#16]

**Comment by nobu-g** [comment]
それは思った
けど曲開始時のスピードを一定にすると、テーゼとかは途中から超速になっちゃうねんな
そういう例外はbmsで指定できるようにするか？

**Comment by chomin** [comment]
基準のBPMを一番長いものにしたりとか、速度の相対変化の倍率をうまく調整するとかはどう？

**Comment by nobu-g** [comment]
持続時間長いのを基準BPMにするわ

**Comment by chomin** [comment]
閉じていい？

**Comment by nobu-g** [comment]
こんな感じでいいならどうぞ
