### ISSUE TITLE
Readerの作成

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#167]
HeaderのreadBMS()とMusicのreadFile()をReader.readBMS()で行うようにしたい。

staticにして、Appdelegateから実行できるようにし、realmのschemaのアップデート時に実行できるようにしたい.

**Comment by chomin** [comment]
https://realm.io/docs/swift/latest/#migrations

**Comment by chomin** [comment]
ついでにrealmを3.10.0にアプデしてみたい

**Comment by nobu-g** [comment]
あんま分かってないけどrealmのschemaのアップデート時に実行できると何が嬉しい？
migrationせずにいちいちdeleteAllしてもいい気もする

**Comment by chomin** [comment]
今のままだと双方が手動でdeleteAll()する必要があるから伝え忘れたりすると混乱するし、
プルリク出した後、マージ前に別のブランチで(アプデ前のバージョンで)作業しマージ後にrebaseとかした場合もdeleteAll()する必要があるからめんどくさい。

まあdeleteAll()のかわりにアプリそのものを消しても良さそう。(ただし逐一認証しなおす必要があるからめんどくさい)

バージョンを戻す時はアプリ消すしかなさそうやけどね。


2018/09/25 11:54、nobu-g <notifications@github.com>のメール:

あんま分かってないけどrealmのschemaのアップデート時に実行できると何が嬉しい？
migrationせずにいちいちdeleteAllしてもいい気もする

**Comment by chomin** [comment]
あと、同じような処理が別々の場所に書かれてるってのは関数化した意味()ってなる

2018/09/25 11:54、nobu-g <notifications@github.com>のメール:

あんま分かってないけどrealmのschemaのアップデート時に実行できると何が嬉しい？
migrationせずにいちいちdeleteAllしてもいい気もする

**Comment by nobu-g** [comment]
AppDelegateでreadBMSが呼べれば、手動でdeleteAllしなくていい？

**Comment by chomin** [comment]
そのとおり

マージしたときに、bmsファイル自体の編集をしてないからファイルの再読込は行われてなくて、新しいプロパティにデフォルトの値が入ったままになってるから、読み込ませればdeleteAll()する必要がなくなると思う。

ただし、realmオブジェクトのプロパティをいじるたびに新しい値として何をいれるかみたいなコードを書く必要はある。

**Comment by nobu-g** [comment]
> マージしたときに、bmsファイル自体の編集をしてないから
これってVIDEOIDいじった時の話やんな
今後Realmオブジェクト変更するとしたらbmsも変更されてるのでは？

**Comment by chomin** [comment]
```let config = Realm.Configuration(deleteRealmIfMigrationNeeded: true)
Realm.Configuration.defaultConfiguration = config```

かな。多分deleteAll()と一緒の挙動になりそう。

schemaVersionを上げる方式だとコードに履歴みたいなのが残るからnobuが好きそうやと思ったけどそうでもないのかな

`deleteRealmIfMigrationNeeded: true`にする？

**Comment by chomin** [comment]
まあ現に今までもbmsの変更を伴ってたしそのほうが多いと思うんやけど、備えあれば憂いなしって感じかな

**Comment by nobu-g** [comment]
コードに履歴？

**Comment by chomin** [comment]
> realmオブジェクトのプロパティをいじるたびに新しい値として何をいれるかみたいなコード

例えば今回なら

```
if oldSchemaVersion < 5 {
                    migration.enumerateObjects(
                        ofType: Header.className(),
                        { (oldObject, newObject) in
                            let fileName = oldObject!["bmsNameWithExtension"] as! String
                            newObject!["videoID"] = (ファイルから読み込まれたid)
                            newObject!["videoID2"] = (ファイルから読み込まれたid)
                    })
                }
```

って感じで、コードを見たらvideoIDとvideoID2が加わったんやなって分かる

**Comment by chomin** [comment]
んで次のアプデで

```
if oldSchemaVersion < 6 {
                    migration.enumerateObjects(
                        ofType: (変更したオブジェクトのクラス名),
                        { (oldObject, newObject) in

                    })
                }

```

ってのが追加される。。。
って感じ

**Comment by nobu-g** [comment]
んー
修正するたびにコード増えていくのは嫌かなあ

migrationの時しか使われへんコードやし

**Comment by chomin** [comment]
おｋ

んじゃ消す方向で
