### ISSUE TITLE
ダウンロード画面のUIを考えよう

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#178]
- クルクル回すだけにするかゲージにするか
- （ゲージにするなら）形は円か棒か
- 容量を表示するか
- 割合を表示するか
- ファイル名を表示するか
- ファイル数を表示するか

**Comment by nobu-g** [comment]
そんなに待たないからゲージにしなくてもいい気がする
[これ](https://github.com/SVProgressHUD/SVProgressHUD)とか
