### ISSUE TITLE
YouTubeモードでノーツがずれる

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#44]
特に曲の最初で
カクッと

**Comment by chomin** [comment]
とりあえず

独自にタイマーを動かす→ムービーがずれたら独自タイマーに合わせてムービーを修正する

って感じでいいかな

**Comment by nobu-g** [comment]
もうちょっと根本的に直せないかなあ

**Comment by chomin** [comment]
なんかアイデアある？

**Comment by chomin** [comment]
結局これどうなったん

**Comment by nobu-g** [comment]
YouTubeのタイマーは使い物にならん→独自タイマー作るしかない→BGMのタイマー使える？

長所
変数が減る

短所
可読性が落ちる(BGMって名前やのにタイマーなんか…(困惑))
→対策
YouTubeをミュートにして音はBGMに任せる？(映像とタイミング合わせる必要あり)


とか考えてた

**Comment by chomin** [comment]
自動再生してると、

判定前→後判定時間の後

って飛び方するとlane.isJudgeRangeがfalseになるので判定できなくなる

**Comment by chomin** [comment]
YTPlayerを拡張して、独自タイマーを作る。
映像との同期は(もとから入っている方の)タイマーのcurrentTimeを利用する。
以後は独自タイマーを見ながらノーツを動かす。

(余力があれば、映像がずれたときは独自タイマーから時間を取得して映像の再生位置を調整する？)

**Comment by chomin** [comment]
YouTubeモードで、bmsからbgmの再生開始タイミングを指定してる分の調整はどこでやってる？

**Comment by nobu-g** [comment]
なんの調整？
YouTubeモードやのにbgm？

**Comment by chomin** [comment]
bmsで1チャンネルの二つ目の10でYouTube再生pos指定してるやん

それの調整

**Comment by nobu-g** [comment]
たしか最初はその時間分待って再生してたけど、再生開始してから実際再生されるまで暫くかかってて、結局待たんでも一緒やんってなった。
それでも譜面とYouTubeが同期してるのはupdateでmediaOffsetTime足してるから

**Comment by chomin** [comment]
サンキュー

独自タイマー導入してからめっちゃずれて、bmsで動かしても変わってない気がしたから帰ったらどうなってんのか調べてみるわ

**Comment by chomin** [comment]
currentTime>0になった瞬間にポーズして、そこからタイマースタートしてmedia Offset Time後に動画スタート
