### ISSUE TITLE
たまに判定されない

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#70]
特にFlickEndが顕著？

**Comment by chomin** [comment]
普通にタップした位置が上過ぎるとかじゃないん？
（前にも同じような症状があったときは、ボタンの縦の長さを変更したら直ったけど。。。）

**Comment by nobu-g** [comment]
なんかなあ
とりま保留で

**Comment by chomin** [comment]
とりあえず範囲広げてみるか
