### ISSUE TITLE
スピード変化の実装

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#73]
20チャンネルで、16進数一桁ずつの浮動小数点表示によって対応するノーツの速さの倍率を変化させる。仮数部は符号なし、指数部は符号付き2進数をそのまま16進数で表現する。例えば、bms上で'10'なら1倍、'59'なら0.5倍である。この方法だと0.75倍みたいなのは指定できない？

**Comment by chomin** [comment]
@nobu-g 
やっぱり細かすぎて無駄な値が多すぎる(10^(-7)とか使わなさそう)ので変更。

シンプルに、16進数二桁の値を1/8倍した倍率でノーツを動かすってのはどう？
例えば、08が1倍で、01が0.125倍みたいな感じ

**Comment by nobu-g** [comment]
それやったら1/16単位でよくない？
10が1倍、20が2倍で分かりやすい

**Comment by chomin** [comment]
んじゃそうしよか
