### ISSUE TITLE
重い

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#8]
何もないところで画面を連打すると最大5fpsくらい減る
This gameで画面を一切触らなくても30fpsくらいまで減る事がある

フレーム数を30fps以下に制限すべき？

**Comment by nobu-g** [comment]
描画が重い？それとも判定？

**Comment by chomin** [comment]
描画かな。
ノーツ詰まってるところで普通にプレイするとカックカクになる

**Comment by nobu-g** [comment]
どこが負荷なのか…
一回setPos関数をめっちゃ簡単にしてみたり？

**Comment by chomin** [comment]
せやな。ロングに必要なのは位置と横幅だけやからら、縦幅の演算と描写、拡大、縮小の処理の頻度を下げるとこからかな。
