### ISSUE TITLE
bgmモードで一時停止しても止まらない

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#82]

**Comment by chomin** [comment]
bgmは止まってるけどノーツが止まってない

**Comment by chomin** [comment]
bgmの再生前に止めるとcurrentTimeが0.0だから、update()内の

`if BGM.currentTime > 0 `

に入らないのが原因っぽい。直しとくわ

**Comment by nobu-g** [comment]
この辺は#44と合わせて考えなあかん

**Comment by chomin** [comment]
timerの仕組みとかもよく分からんし今度教えて

**Comment by nobu-g** [comment]
おけ
今週は忙しかったわ;;
