### ISSUE TITLE
YouTubeが再生が終了せずとも演奏を終われるようにする

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#87]

**Comment by nobu-g** [comment]
細かい仕様どんなんやっけ

**Comment by chomin** [comment]
BGMプレイヤーの再生終了通知を受け取ったらシーン移動する
って感じやと思う

**Comment by nobu-g** [comment]
BMSファイルに終了命令入れるとかじゃ？

**Comment by chomin** [comment]
変更後の話ね

それであってる

2018/08/18 13:13、nobu-g <notifications@github.com>のメール:

BMSファイルに終了命令入れるとかじゃ？

**Comment by nobu-g** [comment]
それの詳細を

**Comment by chomin** [comment]
01チャンネルの11で指定する

2018/08/18 14:05、nobu-g <notifications@github.com>のメール:

それの詳細を

**Comment by nobu-g** [comment]
BGM, YouTube1, Youtube2の楽曲開始命令をそれぞれ01チャンネルの10, 20, 30にしようとおもうねんけどどう？

**Comment by chomin** [comment]
確か今って01チャンネルの10で書かれた順番で認識してるんやっけ

あり

2018/08/22 2:46、nobu-g <notifications@github.com>のメール:

BGM, YouTube1, Youtube2の楽曲開始命令をそれぞれ01チャンネルの10, 20, 30にしようとおもうねんけどどう？

**Comment by nobu-g** [comment]
順番やと分かりにくいし複数行書かなあかんし

**Comment by chomin** [comment]
ただタイミングがかぶる時を考慮して複数行でも許容せなあかんよね

2018/08/22 3:04、nobu-g <notifications@github.com>のメール:

順番やと分かりにくいし複数行書かなあかんし

**Comment by nobu-g** [comment]
もち複数行も許容する
でもタイミング同じ場合は数字大きい方を書かなくていいようにするつもり
