### ISSUE TITLE
設定ボタンが表示されない

### ISSUE THREAD

**Issue by nobu-g** [chomin/Music-Game#89]
2曲目以降は表示される

**Comment by chomin** [comment]
Dimensions.makeInstanceをするのがGameSceneに移ってからになったのが原因やな。iconButtonSizeが0になってる。

とりあえずGameViewControllerでもlaneNumを適当に入れて実装するか、laneNumの無いmakeInstance関数も実装するかどっちがいい？

**Comment by chomin** [comment]
とりあえず任せるわ

**Comment by nobu-g** [comment]
ChooseMusicSceneのdidMove内が問題やから、そこでローカル変数iconButtonSize作るのはどう？
frame.width/16って2回書かなあかんけど

**Comment by chomin** [comment]
GameSceneのpauseButtonと大きさ揃えたいし、コードクローンはできるだけなくしたいからどこからでも呼び出せるようにしたいねんな

**Comment by nobu-g** [comment]
だめかー
じゃあ、DimensionsクラスにupdateInstance(laneNum: Int)作ろう
createInstanceは引数frameだけにして
あと、instanceがnilじゃなかったらcreateできないようにする

**Comment by chomin** [comment]
おけ

頼んだ
