### ISSUE TITLE
touches系の処理の一部を関数にまとめる

### ISSUE THREAD

**Issue by chomin** [chomin/Music-Game#99]
最近ノーツを探索し対象ノーツを返す関数を作る。
その際、ノーツをソートしている箇所をソートせず.min関数を利用してノーツを決める。

**Comment by nobu-g** [comment]
判定周りスッキリさせて欲しいm(__)m

**Comment by chomin** [comment]
おｋ
今やってるとこ終わったらやるわ

**Comment by chomin** [comment]
最近ノーツを探すやつって2箇所に記述されてて、対象ノーツの種類も違うから関数化するメリットが良く分からん。。。

.minを使うってのは結局minしか使わないから処理を減らそうって感じだったっけ

**Comment by nobu-g** [comment]
似たような処理やから纏められると読みやすいかなと思っただけで、コードが汚くなるなら無理にやらんでもいいよ

minは負荷軽減より可読性向上

あとはコメントアウトがそのまま残ってるのとか直して欲しいかな
とにかく全体的に読みやすくなればいいかなーという所
